"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
MODULES = ['helper', 'sprites']
APP = ['game.py']
DATA_FILES = ['fonts','img','snd','data','dependencies']
OPTIONS = {'argv_emulation': True}

setup(
    py_modules = MODULES,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
